### PR TITLE
Support for PHPUnit 6

### PR DESCRIPTION
**Pull request by angelov**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes?
| BC breaks?      | yes
| Related tickets | #86 
| License         | MIT

This changes the library to work only with PHPUnit 6. Support for older versions is dropped, as suggested by @michalmarcinkowski on [Twitter](https://twitter.com/micmarcinkowski/status/872402441383424000).

Note that PHPUnit 6 requires PHP 7.0+.

### CODE REVIEW

**Comment by michalmarcinkowski** [comment]
Hi Dejan!

Thanks for PR! Could you also remove PHP 5.6 and HHVM from `.travis` [file](https://github.com/Lakion/ApiTestCase/blob/master/.travis.yml#L13-L14) as well as bump requirements to `php: ^7.0` in composer.json?

**Comment by angelov** [comment]
@michalmarcinkowski done :)

**Comment by michalmarcinkowski** [comment]
@lchrusciel there were just little changes since v1.1, nothing really important. I think we don't need to release v1.2 and can go with v2.0 tag, wdyt?

**Comment by lchrusciel** [comment]
@michalmarcinkowski I just tagged 1.2 with TMP_DIR to give this feature for people which will stay with PHPUnit 5.7 and PHP 5.6. I would like to decouple ApiTestCase before 2.0 because can produce some BC-Breaks and use Traits instead of server variables, but I don't know when I will find a time for this. So v2 with PHP 7 and PHPUnit 6 seems also correct.

**Comment by bendavies** [comment]
what's stopping this from progressing?

**Comment by lchrusciel** [comment]
TBH, nothing.

**Comment by lchrusciel** [comment]
Thanks Dejan :)

**Comment by bendavies** [comment]
nice!

**Comment by michalmarcinkowski** [comment]
Well done @angelov! Thanks @lchrusciel for quick response! 👍

**Comment by angelov** [comment]
:beers:

**Pull request merged**
