### PR TITLE
Allow installation of PHPUnit 7.0

### PR DESCRIPTION
**Pull request by emodric**
It would be great if this could end up in 3.0, since PHPUnit 7.0 is released in two weeks time :)

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Related tickets | N/A
| License         | MIT

### CODE REVIEW

**Comment by lchrusciel** [comment]
I'm totally ok with this change, but travis is still installing 6.x version(https://travis-ci.org/Lakion/ApiTestCase/jobs/330759426#L548). In which stage is the phpunit? rc? Maybe we can add it to composer merge it to master and in two weeks I will release a new version with a support to stable version

**Comment by emodric** [comment]
There are no tagged versions of 7.0 yet, if that's what you're asking, but Sebastian tweeted this https://twitter.com/s_bergmann/status/954245050392866816

Your suggestion is fine with me, as long as I can install it :)

**Comment by lchrusciel** [comment]
What would you say if I would create a new branch for it?

**Comment by pamil** [comment]
You might want to use something like https://github.com/Sylius/Sylius/blob/master/etc/travis/suites/application/install.sh#L7-L8 to run tests for both PHPUnit 6 and 7. If the 7.0 build fails, then just allow it to fail on Travis and monitor if it starts to pass by using cron Travis builds every 24h 🎉

**Comment by emodric** [comment]
@lchrusciel It's fine, yes :)

But if it matters, I've ran the tests on PHPUnit 7 and they pass:

```
eddie@abyss [~/www/api-test-case] ( ± master v3.0.0-RC.2 ● ) $ git diff
diff --git a/composer.json b/composer.json
index e1466f1..e92c53c 100644
--- a/composer.json
+++ b/composer.json
@@ -32,13 +32,15 @@
         "doctrine/orm": "^2.5",
         "nelmio/alice": "^3.1",
         "phpspec/php-diff": "^1.1",
-        "phpunit/phpunit": "^6.0",
+        "phpunit/phpunit": "dev-master",
         "polishsymfonycommunity/symfony-mocker-container": "^1.0",
         "symfony/browser-kit": "^3.2|^4.0",
         "symfony/finder": "^3.2|^4.0",
         "symfony/framework-bundle": "^3.3|^4.0",
         "theofidry/alice-data-fixtures": "^1.0"
     },
+    "minimum-stability": "dev",
+    "prefer-stable": true,
     "require-dev": {
         "symfony/serializer": "^3.2|^4.0"
     },
eddie@abyss [~/www/api-test-case] ( ± master v3.0.0-RC.2 ● ) $ test/app/console doctrine:schema:update --force -vvv
2018-01-19T15:46:40+01:00 [debug] SELECT name FROM sqlite_master WHERE type = 'table' AND name != 'sqlite_sequence' AND name != 'geometry_columns' AND name != 'spatial_ref_sys' UNION ALL SELECT name FROM sqlite_temp_master WHERE type = 'table' ORDER BY name

 Updating database schema...

2018-01-19T15:46:40+01:00 [debug] SELECT name FROM sqlite_master WHERE type = 'table' AND name != 'sqlite_sequence' AND name != 'geometry_columns' AND name != 'spatial_ref_sys' UNION ALL SELECT name FROM sqlite_temp_master WHERE type = 'table' ORDER BY name
2018-01-19T15:46:40+01:00 [debug] CREATE TABLE test_product (id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, price INTEGER NOT NULL, PRIMARY KEY(id))
     1 query was executed

                                                                                                                        
 [OK] Database schema updated successfully!                                                                             
                                                                                                                        

eddie@abyss [~/www/api-test-case] ( ± master v3.0.0-RC.2 ● ) $ bin/phpunit 
PHPUnit 7.0-g019753968 by Sebastian Bergmann and contributors.

2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_use_third_party_api".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_product_index".
2018-01-19T15:46:51+01:00 [debug] SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3 FROM test_product t0
.2018-01-19T15:46:51+01:00 [info] Matched route "app_product_show".
2018-01-19T15:46:51+01:00 [debug] SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3 FROM test_product t0 WHERE t0.id = ?
.2018-01-19T15:46:51+01:00 [info] Matched route "app_product_create".
2018-01-19T15:46:51+01:00 [debug] "START TRANSACTION"
2018-01-19T15:46:51+01:00 [debug] INSERT INTO test_product (name, price) VALUES (?, ?)
2018-01-19T15:46:51+01:00 [debug] "COMMIT"
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_hello_world".
.2018-01-19T15:46:51+01:00 [info] Matched route "app_use_third_party_api".
.2018-01-19T15:46:51+01:00 [info] Purging database with purge mode "DELETE_MODE".
2018-01-19T15:46:51+01:00 [info] Loading fixtures.
2018-01-19T15:46:51+01:00 [info] Pre-processing objects.
2018-01-19T15:46:51+01:00 [info] Flushing objects.
2018-01-19T15:46:51+01:00 [info] Post-processing objects.
2018-01-19T15:46:51+01:00 [info] Done.
2018-01-19T15:46:51+01:00 [info] Matched route "app_product_index".
2018-01-19T15:46:51+01:00 [debug] SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3 FROM test_product t0
.2018-01-19T15:46:51+01:00 [info] Purging database with purge mode "DELETE_MODE".
2018-01-19T15:46:51+01:00 [info] Loading fixtures.
2018-01-19T15:46:51+01:00 [info] Pre-processing objects.
2018-01-19T15:46:51+01:00 [info] Flushing objects.
2018-01-19T15:46:51+01:00 [info] Post-processing objects.
2018-01-19T15:46:51+01:00 [info] Done.
2018-01-19T15:46:51+01:00 [info] Matched route "app_product_show".
2018-01-19T15:46:51+01:00 [debug] SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3 FROM test_product t0 WHERE t0.id = ?
.                                                   15 / 15 (100%)

Time: 470 ms, Memory: 22.00MB

OK (15 tests, 34 assertions)
eddie@abyss [~/www/api-test-case] ( ± master v3.0.0-RC.2 ● ) $ 
```

**Comment by lchrusciel** [comment]
Edi, I hope you didn't mind, that I have added a job to test against PHPUnit 7.0 to your branch.

**Comment by emodric** [comment]
Not at all :)

**Comment by lchrusciel** [comment]
Thanks Edi! dev-master will be tested against PHPUnit 7.0 then :D I'm waiting with the next RC for the release :)

**Comment by emodric** [comment]
Great! Thanks Łukasz!

**Comment by emodric** [comment]
@lchrusciel PHPUnit 7.0 is released. Is this ready for 3.0 final ? :)

**Pull request merged**
